INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Afghanistan', 'AF', 'U+1F1E6 U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Africa', 'AF', '');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Åland Islands', 'AX', 'U+1F1E6 U+1F1FD');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Albania', 'AL', 'U+1F1E6 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Algeria', 'DZ', 'U+1F1E9 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('American Samoa', 'AS', 'U+1F1E6 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Andorra', 'AD', 'U+1F1E6 U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Angola', 'AO', 'U+1F1E6 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Anguilla', 'AI', 'U+1F1E6 U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Antarctica', 'AQ', 'U+1F1E6 U+1F1F6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Antigua and Barbuda', 'AG', 'U+1F1E6 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Argentina', 'AR', 'U+1F1E6 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Armenia', 'AM', 'U+1F1E6 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Asia', 'AS', '');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Aruba', 'AW', 'U+1F1E6 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Australia', 'AU', 'U+1F1E6 U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Austria', 'AT', 'U+1F1E6 U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Azerbaijan', 'AZ', 'U+1F1E6 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bahamas', 'BS', 'U+1F1E7 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bahrain', 'BH', 'U+1F1E7 U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bangladesh', 'BD', 'U+1F1E7 U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Barbados', 'BB', 'U+1F1E7 U+1F1E7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Belarus', 'BY', 'U+1F1E7 U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Belgium', 'BE', 'U+1F1E7 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Belize', 'BZ', 'U+1F1E7 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Benin', 'BJ', 'U+1F1E7 U+1F1EF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bermuda', 'BM', 'U+1F1E7 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bhutan', 'BT', 'U+1F1E7 U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bolivia', 'BO', 'U+1F1E7 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bosnia and Herzegovina', 'BA', 'U+1F1E7 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Botswana', 'BW', 'U+1F1E7 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bouvet Island', 'BV', 'U+1F1E7 U+1F1FB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Brazil', 'BR', 'U+1F1E7 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('British Indian Ocean Territory', 'IO', 'U+1F1EE U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Brunei', 'BN', 'U+1F1E7 U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Bulgaria', 'BG', 'U+1F1E7 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Burkina Faso', 'BF', 'U+1F1E7 U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Burundi', 'BI', 'U+1F1E7 U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cambodia', 'KH', 'U+1F1F0 U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cameroon', 'CM', 'U+1F1E8 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Canada', 'CA', 'U+1F1E8 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cape Verde', 'CV', 'U+1F1E8 U+1F1FB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Caribbean Netherlands', 'BQ', 'U+1F1E7 U+1F1F6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cayman Islands', 'KY', 'U+1F1F0 U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Central African Republic', 'CF', 'U+1F1E8 U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Chad', 'TD', 'U+1F1F9 U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Chile', 'CL', 'U+1F1E8 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('China', 'CN', 'U+1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Christmas Island', 'CX', 'U+1F1E8 U+1F1FD');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cocos (Keeling) Islands', 'CC', 'U+1F1E8 U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Colombia', 'CO', 'U+1F1E8 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Comoros', 'KM', 'U+1F1F0 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Republic of the Congo', 'CG', 'U+1F1E8 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('DR Congo', 'CD', 'U+1F1E8 U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cook Islands', 'CK', 'U+1F1E8 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Costa Rica', 'CR', 'U+1F1E8 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cote dIvoire (Ivory Coast)', 'CI', 'U+1F1E8 U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Croatia', 'HR', 'U+1F1ED U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cuba', 'CU', 'U+1F1E8 U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Curaçao', 'CW', 'U+1F1E8 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Cyprus', 'CY', 'U+1F1E8 U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Czechia', 'CZ', 'U+1F1E8 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Denmark', 'DK', 'U+1F1E9 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Djibouti', 'DJ', 'U+1F1E9 U+1F1EF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Dominica', 'DM', 'U+1F1E9 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Dominican Republic', 'DO', 'U+1F1E9 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Ecuador', 'EC', 'U+1F1EA U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Egypt', 'EG', 'U+1F1EA U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('El Salvador', 'SV', 'U+1F1F8 U+1F1FB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('England', 'EN', 'U+1F3F4 U+E0067 U+E0062 U+E0065 U+E006E U+E0067 U+E007F');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Equatorial Guinea', 'GQ', 'U+1F1EC U+1F1F6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Eritrea', 'ER', 'U+1F1EA U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Estonia', 'EE', 'U+1F1EA U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Eswatini (Swaziland)', 'SZ', 'U+1F1F8 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Ethiopia', 'ET', 'U+1F1EA U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Europe', 'EU', '');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Falkland Islands', 'FK', 'U+1F1EB U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Faroe Islands', 'FO', 'U+1F1EB U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Fiji', 'FJ', 'U+1F1EB U+1F1EF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Finland', 'FI', 'U+1F1EB U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('France', 'FR', 'U+1F1EB U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('French Guiana', 'GF', 'U+1F1EC U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('French Polynesia', 'PF', 'U+1F1F5 U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('French Southern and Antarctic Lands', 'TF', 'U+1F1F9 U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Gabon', 'GA', 'U+1F1EC U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Gambia', 'GM', 'U+1F1EC U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Georgia', 'GE', 'U+1F1EC U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Germany', 'DE', 'U+1F1E9 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Ghana', 'GH', 'U+1F1EC U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Gibraltar', 'GI', 'U+1F1EC U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Greece', 'GR', 'U+1F1EC U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Greenland', 'GL', 'U+1F1EC U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Grenada', 'GD', 'U+1F1EC U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Guadeloupe', 'GP', 'U+1F1EC U+1F1F5');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Guam', 'GU', 'U+1F1EC U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Guatemala', 'GT', 'U+1F1EC U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Guernsey', 'GG', 'U+1F1EC U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Guinea', 'GN', 'U+1F1EC U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Guinea-Bissau', 'GW', 'U+1F1EC U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Guyana', 'GY', 'U+1F1EC U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Haiti', 'HT', 'U+1F1ED U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Heard Island and McDonald Islands', 'HM', 'U+1F1ED U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Honduras', 'HN', 'U+1F1ED U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Hong Kong', 'HK', 'U+1F1ED U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Hungary', 'HU', 'U+1F1ED U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Iceland', 'IS', 'U+1F1EE U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('India', 'IN', 'U+1F1EE U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Indonesia', 'ID', 'U+1F1EE U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Iran', 'IR', 'U+1F1EE U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Iraq', 'IQ', 'U+1F1EE U+1F1F6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Ireland', 'IE', 'U+1F1EE U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Isle of Man', 'IM', 'U+1F1EE U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Israel', 'IL', 'U+1F1EE U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Italy', 'IT', 'U+1F1EE U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Jamaica', 'JM', 'U+1F1EF U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Japan', 'JP', 'U+1F1EF U+1F1F5');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Jersey', 'JE', 'U+1F1EF U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Jordan', 'JO', 'U+1F1EF U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Kazakhstan', 'KZ', 'U+1F1F0 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Kenya', 'KE', 'U+1F1F0 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Kiribati', 'KI', 'U+1F1F0 U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('North Korea', 'KP', 'U+1F1F0 U+1F1F5');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('South Korea', 'KR', 'U+1F1F0 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Kosovo', 'XK', 'U+1F1FD U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Kuwait', 'KW', 'U+1F1F0 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Kyrgyzstan', 'KG', 'U+1F1F0 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Laos', 'LA', 'U+1F1F1 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Latvia', 'LV', 'U+1F1F1 U+1F1FB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Lebanon', 'LB', 'U+1F1F1 U+1F1E7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Lesotho', 'LS', 'U+1F1F1 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Liberia', 'LR', 'U+1F1F1 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Libya', 'LY', 'U+1F1F1 U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Liechtenstein', 'LI', 'U+1F1F1 U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Lithuania', 'LT', 'U+1F1F1 U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Luxembourg', 'LU', 'U+1F1F1 U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Macau', 'MO', 'U+1F1F2 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Madagascar', 'MG', 'U+1F1F2 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Malawi', 'MW', 'U+1F1F2 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Malaysia', 'MY', 'U+1F1F2 U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Maldives', 'MV', 'U+1F1F2 U+1F1FB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Mali', 'ML', 'U+1F1F2 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Malta', 'MT', 'U+1F1F2 U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Marshall Islands', 'MH', 'U+1F1F2 U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Martinique', 'MQ', 'U+1F1F2 U+1F1F6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Mauritania', 'MR', 'U+1F1F2 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Mauritius', 'MU', 'U+1F1F2 U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Mayotte', 'YT', 'U+1F1FE U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Mexico', 'MX', 'U+1F1F2 U+1F1FD');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Micronesia', 'FM', 'U+1F1EB U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Moldova', 'MD', 'U+1F1F2 U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Monaco', 'MC', 'U+1F1F2 U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Mongolia', 'MN', 'U+1F1F2 U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Montenegro', 'ME', 'U+1F1F2 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Montserrat', 'MS', 'U+1F1F2 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Morocco', 'MA', 'U+1F1F2 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Mozambique', 'MZ', 'U+1F1F2 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Myanmar', 'MM', 'U+1F1F2 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Namibia', 'NA', 'U+1F1F3 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Nauru', 'NR', 'U+1F1F3 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Nepal', 'NP', 'U+1F1F3 U+1F1F5');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Netherlands', 'NL', 'U+1F1F3 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('New Caledonia', 'NC', 'U+1F1F3 U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('New Zealand', 'NZ', 'U+1F1F3 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Nicaragua', 'NI', 'U+1F1F3 U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Niger', 'NE', 'U+1F1F3 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Nigeria', 'NG', 'U+1F1F3 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Niue', 'NU', 'U+1F1F3 U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Norfolk Island', 'NF', 'U+1F1F3 U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('North America', 'NA', 'U+1F1F2 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('North Macedonia', 'MK', 'U+1F1F2 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Northern Mariana Islands', 'MP', 'U+1F1F2 U+1F1F5');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Norway', 'NO', 'U+1F1F3 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Oman', 'OM', 'U+1F1F4 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Pakistan', 'PK', 'U+1F1F5 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Palau', 'PW', 'U+1F1F5 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Palestine', 'PS', 'U+1F1F5 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Panama', 'PA', 'U+1F1F5 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Papua New Guinea', 'PG', 'U+1F1F5 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Paraguay', 'PY', 'U+1F1F5 U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Peru', 'PE', 'U+1F1F5 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Philippines', 'PH', 'U+1F1F5 U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Pitcairn Islands', 'PN', 'U+1F1F5 U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Poland', 'PL', 'U+1F1F5 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Portugal', 'PT', 'U+1F1F5 U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Puerto Rico', 'PR', 'U+1F1F5 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Qatar', 'QA', 'U+1F1F6 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Réunion', 'RE', 'U+1F1F7 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Romania', 'RO', 'U+1F1F7 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Russia', 'RU', 'U+1F1F7 U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Rwanda', 'RW', 'U+1F1F7 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saint Barthélemy', 'BL', 'U+1F1E7 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'U+1F1F8 U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saint Kitts and Nevis', 'KN', 'U+1F1F0 U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saint Lucia', 'LC', 'U+1F1F1 U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saint Martin', 'MF', 'U+1F1F2 U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saint Pierre and Miquelon', 'PM', 'U+1F1F5 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saint Vincent and the Grenadines', 'VC', 'U+1F1FB U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Samoa', 'WS', 'U+1F1FC U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('San Marino', 'SM', 'U+1F1F8 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('São Tomé and Príncipe', 'ST', 'U+1F1F8 U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Saudi Arabia', 'SA', 'U+1F1F8 U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Scotland', 'SC', 'U+1F3F4 U+E0067 U+E0062 U+E0073 U+E0063 U+E0074 U+E007F');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Senegal', 'SN', 'U+1F1F8 U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Serbia', 'RS', 'U+1F1F7 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Seychelles', 'SC', 'U+1F1F8 U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Sierra Leone', 'SL', 'U+1F1F8 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Singapore', 'SG', 'U+1F1F8 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Sint Maarten', 'SX', 'U+1F1F8 U+1F1FD');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Slovakia', 'SK', 'U+1F1F8 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Slovenia', 'SI', 'U+1F1F8 U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Solomon Islands', 'SB', 'U+1F1F8 U+1F1E7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Somalia', 'SO', 'U+1F1F8 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('South Africa', 'ZA', 'U+1F1FF U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('South Sudan', 'SS', 'U+1F1F8 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('South Georgia', 'GS', 'U+1F1EC U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('South America', 'SA', 'U+1F1F8 U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Spain', 'ES', 'U+1F1EA U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Sri Lanka', 'LK', 'U+1F1F1 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Sudan', 'SD', 'U+1F1F8 U+1F1E9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Suriname', 'SR', 'U+1F1F8 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Svalbard and Jan Mayen', 'SJ', 'U+1F1F8 U+1F1EF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Sweden', 'SE', 'U+1F1F8 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Switzerland', 'CH', 'U+1F1E8 U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Syria', 'SY', 'U+1F1F8 U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Taiwan', 'TW', 'U+1F1F9 U+1F1FC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Tajikistan', 'TJ', 'U+1F1F9 U+1F1EF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Tanzania', 'TZ', 'U+1F1F9 U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Thailand', 'TH', 'U+1F1F9 U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Timor-Leste', 'TL', 'U+1F1F9 U+1F1F1');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Togo', 'TG', 'U+1F1F9 U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Tokelau', 'TK', 'U+1F1F9 U+1F1F0');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Tonga', 'TO', 'U+1F1F9 U+1F1F4');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Trinidad and Tobago', 'TT', 'U+1F1F9 U+1F1F9');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Tunisia', 'TN', 'U+1F1F9 U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Turkey', 'TR', 'U+1F1F9 U+1F1F7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Turkmenistan', 'TM', 'U+1F1F9 U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Turks and Caicos Islands', 'TC', 'U+1F1F9 U+1F1E8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Tuvalu', 'TV', 'U+1F1F9 U+1F1FB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Uganda', 'UG', 'U+1F1FA U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Ukraine', 'UA', 'U+1F1FA U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('United Arab Emirates', 'AE', 'U+1F1E6 U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('United Kingdom', 'GB', 'U+1F1EC U+1F1E7');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('United States', 'US', 'U+1F1FA U+1F1F8');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('United States Minor Outlying Islands', 'UM', 'U+1F1FA U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Uruguay', 'UY', 'U+1F1FA U+1F1FE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Uzbekistan', 'UZ', 'U+1F1FA U+1F1FF');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Vanuatu', 'VU', 'U+1F1FB U+1F1FA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Vatican City (Holy See)', 'VA', 'U+1F1FB U+1F1E6');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Venezuela', 'VE', 'U+1F1FB U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Vietnam', 'VN', 'U+1F1FB U+1F1F3');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('British Virgin Islands', 'VG', 'U+1F1FB U+1F1EC');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('United States Virgin Islands', 'VI', 'U+1F1FB U+1F1EE');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Wales', 'WA', 'U+1F3F4 U+E0067 U+E0062 U+E0077 U+E006C U+E0073 U+E007F');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Wallis and Futuna', 'WF', 'U+1F1FC U+1F1EB');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Western Sahara', 'EH', 'U+1F1EA U+1F1ED');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Yemen', 'YE', 'U+1F1FE U+1F1EA');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Zambia', 'ZM', 'U+1F1FF U+1F1F2');
INSERT INTO public."Countries" ("Name", "AbbreviatedName", "CountryImage") VALUES ('Zimbabwe', 'ZW', 'U+1F1FF U+1F1FC');